In [2]:
#1D array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
#2D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
#3D array with two 2D arrays
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
#ndim attribute
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
#accessing array elements in 1D array
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[4])

5


In [12]:
#get the second and third index of the elements and add them
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2]+arr[3])

7


In [14]:
#Accessing 2D arrays
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element 1st row: ",arr[0,1])
print("1st element 2nd row: ",arr[1,0])

2nd element 1st row:  2
1st element 2nd row:  6


In [19]:
#Slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:3])

[2 3]


In [20]:
#when start and end both index are not mentioned
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:])

[1 2 3 4 5 6 7]


In [22]:
#Negative Slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [23]:
#slicing using step
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [24]:
#Return every other element from the entire array
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]
