In [2]:
#Slicing 2D arrays
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [4]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
element=arr[1,2]
print(element)

6


In [5]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
row_slice=arr[0:2]
print(row_slice)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
col_slice=arr[:,1:3]
print(col_slice)

[[2 3]
 [5 6]
 [8 9]]
